/**
 * Build a printable personnel-file packet PDF for one employee.
 *
 * Covers every personnel record (admin-only output — caller MUST be
 * authenticated as admin). Each record is rendered with its metadata,
 * attachments list, and acknowledgment state.
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { PersonnelRecord, PersonnelAttachment } from "./personnel";

export interface PacketInput {
  employee: {
    id: string;
    firstName: string;
    lastName: string;
    certification: string | null;
    position: string | null;
    hireDate: string | null;
    photoUrl: string | null;
  };
  records: PersonnelRecord[];
  attachmentsByRecord: Record<string, PersonnelAttachment[]>;
  generatedBy: string;
}

const CATEGORY_LABELS: Record<string, string> = {
  conduct: "Conduct & Discipline",
  performance: "Performance & Coaching",
  attendance: "Attendance & Scheduling",
  accommodations: "Accommodations & Restrictions",
  clinical: "Clinical / Operational Review",
  positive: "Positive Recognition",
  attachments: "Attachments & Archived",
};

const SEVERITY_COLORS: Record<string, [number, number, number]> = {
  critical: [220, 38, 38],
  serious: [220, 38, 38],
  moderate: [217, 119, 6],
  minor: [217, 119, 6],
  coaching: [37, 99, 235],
  informational: [100, 116, 139],
};

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-US", {
    timeZone: "America/Chicago",
    month: "short", day: "numeric", year: "numeric",
  });
}

export function buildPersonnelPacketPdf(input: PacketInput): Buffer {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  // ── Cover page ─────────────────────────────────────────────────
  doc.setFillColor(4, 13, 26);
  doc.rect(0, 0, W, H, "F");
  doc.setTextColor(240, 180, 41);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("MILLSTADT EMS · PERSONNEL FILE PACKET", 48, 60);

  doc.setTextColor(255);
  doc.setFontSize(32);
  doc.text(`${input.employee.firstName} ${input.employee.lastName}`, 48, 110);

  doc.setFontSize(13);
  doc.setTextColor(203, 213, 225);
  doc.text(input.employee.certification ?? "—", 48, 134);
  if (input.employee.position) doc.text(input.employee.position, 48, 152);

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text(`Hire date: ${fmtDate(input.employee.hireDate)}`, 48, 184);
  doc.text(`Records: ${input.records.length}`, 48, 200);
  doc.text(`Generated: ${new Date().toLocaleString("en-US", { timeZone: "America/Chicago" })}`, 48, 216);
  doc.text(`Generated by: ${input.generatedBy}`, 48, 232);

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const disclaimer = doc.splitTextToSize(
    "CONFIDENTIAL — Personnel file packet. For internal HR / leadership use only. " +
    "Contains protected employment information. Do not distribute outside authorized roles.",
    W - 96,
  );
  doc.text(disclaimer, 48, H - 80);

  // ── Summary table ──────────────────────────────────────────────
  doc.addPage();
  doc.setTextColor(20, 30, 60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Summary", 48, 60);

  const byCat = new Map<string, PersonnelRecord[]>();
  for (const r of input.records) {
    const arr = byCat.get(r.category) ?? [];
    arr.push(r);
    byCat.set(r.category, arr);
  }
  const summary = Array.from(byCat.entries()).map(([cat, list]) => [
    CATEGORY_LABELS[cat] ?? cat,
    String(list.length),
    String(list.filter((r) => r.status === "active").length),
    String(list.filter((r) => r.followUpRequired && !r.followUpCompletedAt).length),
    String(list.filter((r) => r.acknowledgmentRequired && !r.acknowledgedAt).length),
  ]);

  autoTable(doc, {
    startY: 80,
    head: [["Category", "Total", "Active", "Open follow-up", "Pending ack"]],
    body: summary,
    styles: { fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [240, 180, 41], textColor: 20, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  // ── Records (grouped by category) ─────────────────────────────
  for (const [cat, list] of byCat) {
    doc.addPage();
    let y = 60;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(20, 30, 60);
    doc.text(CATEGORY_LABELS[cat] ?? cat, 48, y); y += 6;
    doc.setLineWidth(0.5);
    doc.setDrawColor(240, 180, 41);
    doc.line(48, y, W - 48, y); y += 18;

    for (const r of list) {
      if (y > H - 180) { doc.addPage(); y = 60; }
      y = renderRecord(doc, r, input.attachmentsByRecord[r.id] ?? [], y, W);
      y += 14;
    }
  }

  return Buffer.from(doc.output("arraybuffer"));
}

function renderRecord(
  doc: jsPDF,
  r: PersonnelRecord,
  attachments: PersonnelAttachment[],
  yStart: number,
  W: number,
): number {
  let y = yStart;

  // Card background
  const cardX = 48;
  const cardW = W - 96;
  const startY = y;

  // Title row
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(20, 30, 60);
  const titleLines = doc.splitTextToSize(r.title, cardW - 140);
  doc.text(titleLines, cardX + 14, y + 22);

  // Severity pill
  const sev = SEVERITY_COLORS[r.severity] ?? [100, 116, 139];
  doc.setFillColor(...sev);
  doc.roundedRect(cardX + cardW - 110, y + 8, 96, 18, 4, 4, "F");
  doc.setTextColor(255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text(r.severity.toUpperCase(), cardX + cardW - 62, y + 21, { align: "center" });

  y += 22 + 14 * titleLines.length;

  // Meta line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(75, 85, 99);
  const meta = [
    r.recordType,
    `Status: ${r.status}`,
    r.incidentDate ? `Event: ${fmtDate(r.incidentDate)}` : null,
    `Created: ${fmtDate(r.createdAt)}`,
    r.employeeVisible ? "Employee-visible" : null,
    r.restrictedVisibility ? "HR-only" : null,
    r.followUpRequired ? `Follow-up: ${fmtDate(r.followUpDueDate)}${r.followUpCompletedAt ? " (done)" : " (open)"}` : null,
    r.acknowledgmentRequired ? (r.acknowledgedAt ? `Acknowledged ${fmtDate(r.acknowledgedAt)}` : "Ack pending") : null,
  ].filter(Boolean).join(" · ");
  const metaLines = doc.splitTextToSize(meta, cardW - 28);
  doc.text(metaLines, cardX + 14, y);
  y += 12 * metaLines.length + 4;

  if (r.summary) {
    y = drawBlock(doc, "Summary", r.summary, cardX, cardW, y);
  }
  if (r.actionTaken) {
    y = drawBlock(doc, "Action taken", r.actionTaken, cardX, cardW, y);
  }
  if (r.workLimitations) {
    y = drawBlock(doc, "Work limitations", r.workLimitations, cardX, cardW, y);
  }
  if (r.accommodationType || r.accommodationStart || r.accommodationEnd) {
    const accText =
      [
        r.accommodationType ? `Type: ${r.accommodationType}` : null,
        r.accommodationStart ? `Start: ${fmtDate(r.accommodationStart)}` : null,
        r.accommodationEnd ? `End: ${fmtDate(r.accommodationEnd)}` : null,
        r.accommodationReview ? `Review: ${fmtDate(r.accommodationReview)}` : null,
        r.approvedBy ? `Approved by: ${r.approvedBy}` : null,
      ].filter(Boolean).join(" · ");
    y = drawBlock(doc, "Accommodation", accText, cardX, cardW, y);
  }
  if (r.adminNotes) {
    y = drawBlock(doc, "Admin notes (private)", r.adminNotes, cardX, cardW, y, true);
  }
  if (r.employeeResponse) {
    y = drawBlock(doc, "Employee response", r.employeeResponse, cardX, cardW, y);
  }

  if (attachments.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(75, 85, 99);
    doc.text("Attached files:", cardX + 14, y); y += 12;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(37, 99, 235);
    doc.setFontSize(8);
    for (const a of attachments) {
      const line = `• [${a.visibilityLevel}] ${a.fileName} — ${a.fileUrl}`;
      const lines = doc.splitTextToSize(line, cardW - 28);
      doc.text(lines, cardX + 14, y);
      y += 10 * lines.length;
    }
    y += 4;
  }

  // Card border
  doc.setLineWidth(0.5);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(cardX, startY, cardW, y - startY + 6, 6, 6, "S");
  return y + 6;
}

function drawBlock(doc: jsPDF, label: string, value: string, cardX: number, cardW: number, y: number, muted = false): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(muted ? 148 : 100, muted ? 163 : 116, muted ? 184 : 139);
  doc.text(label.toUpperCase(), cardX + 14, y); y += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(muted ? 100 : 30, muted ? 116 : 41, muted ? 139 : 59);
  const lines = doc.splitTextToSize(value, cardW - 28);
  doc.text(lines, cardX + 14, y);
  y += 12 * lines.length + 6;
  return y;
}
