/**
 * Build a printable personnel-file packet PDF for one employee.
 *
 * Covers every personnel record (admin-only output — caller MUST be
 * authenticated as admin). Each record is rendered with its metadata,
 * attachments list, and acknowledgment state.
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { PersonnelRecord, PersonnelAttachment } from "./personnel";
import { drawContainedImage, loadLogo } from "@/lib/reports/pdf-system";

export interface PacketInput {
  employee: {
    id: string;
    firstName: string;
    lastName: string;
    certification: string | null;
    position: string | null;
    hireDate: string | null;
    photoUrl: string | null;
  };
  records: PersonnelRecord[];
  attachmentsByRecord: Record<string, PersonnelAttachment[]>;
  generatedBy: string;
}

const CATEGORY_LABELS: Record<string, string> = {
  conduct: "Conduct & Discipline",
  performance: "Performance & Coaching",
  attendance: "Attendance & Scheduling",
  accommodations: "Accommodations & Restrictions",
  clinical: "Clinical / Operational Review",
  positive: "Positive Recognition",
  attachments: "Attachments & Archived",
};

const SEVERITY_COLORS: Record<string, [number, number, number]> = {
  critical: [220, 38, 38],
  serious: [220, 38, 38],
  moderate: [217, 119, 6],
  minor: [217, 119, 6],
  coaching: [37, 99, 235],
  informational: [100, 116, 139],
};

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-US", {
    timeZone: "America/Chicago",
    month: "short", day: "numeric", year: "numeric",
  });
}

export async function buildPersonnelPacketPdf(input: PacketInput): Promise<Buffer> {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const logo = await loadLogo();

  // ── Cover page ─────────────────────────────────────────────────
  doc.setFillColor(4, 13, 26);
  doc.rect(0, 0, W, H, "F");
  doc.setTextColor(240, 180, 41);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  if (logo) drawContainedImage(doc, logo.dataUri, "PNG", 48, 40, 58, 58);
  doc.text("MILLSTADT EMS - PERSONNEL FILE PACKET", 122, 72);

  doc.setTextColor(255);
  doc.setFontSize(32);
  const employeeName = `${input.employee.firstName} ${input.employee.lastName}`;
  const nameLines = doc.splitTextToSize(employeeName, W - 96) as string[];
  if (nameLines.length > 1) doc.setFontSize(24);
  doc.text(nameLines, 48, 110);
  const identityY = 110 + (nameLines.length - 1) * 30;

  doc.setFontSize(13);
  doc.setTextColor(203, 213, 225);
  doc.text(input.employee.certification ?? "-", 48, identityY + 24);
  if (input.employee.position) {
    doc.text(doc.splitTextToSize(input.employee.position, W - 96), 48, identityY + 42);
  }

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text(`Hire date: ${fmtDate(input.employee.hireDate)}`, 48, identityY + 74);
  doc.text(`Records: ${input.records.length}`, 48, identityY + 90);
  doc.text(`Generated: ${new Date().toLocaleString("en-US", { timeZone: "America/Chicago", hour12: false })}`, 48, identityY + 106);
  doc.text(doc.splitTextToSize(`Generated by: ${input.generatedBy}`, W - 96), 48, identityY + 122);

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const disclaimer = doc.splitTextToSize(
    "CONFIDENTIAL - Personnel file packet. For internal HR / leadership use only. " +
    "Contains protected employment information. Do not distribute outside authorized roles.",
    W - 96,
  );
  doc.text(disclaimer, 48, H - 80);

  // ── Summary table ──────────────────────────────────────────────
  doc.addPage();
  doc.setTextColor(20, 30, 60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Summary", 48, 60);

  const byCat = new Map<string, PersonnelRecord[]>();
  for (const r of input.records) {
    const arr = byCat.get(r.category) ?? [];
    arr.push(r);
    byCat.set(r.category, arr);
  }
  const summary = Array.from(byCat.entries()).map(([cat, list]) => [
    CATEGORY_LABELS[cat] ?? cat,
    String(list.length),
    String(list.filter((r) => r.status === "active").length),
    String(list.filter((r) => r.followUpRequired && !r.followUpCompletedAt).length),
    String(list.filter((r) => r.acknowledgmentRequired && !r.acknowledgedAt).length),
  ]);

  autoTable(doc, {
    startY: 88,
    head: [["Category", "Total", "Active", "Open follow-up", "Pending ack"]],
    body: summary,
    styles: { fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [240, 180, 41], textColor: 20, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { top: 82, bottom: 54 },
  });

  // ── Records (grouped by category) ─────────────────────────────
  for (const [cat, list] of byCat) {
    doc.addPage();
    let y = 82;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(20, 30, 60);
    doc.text(CATEGORY_LABELS[cat] ?? cat, 48, y); y += 6;
    doc.setLineWidth(0.5);
    doc.setDrawColor(240, 180, 41);
    doc.line(48, y, W - 48, y); y += 18;

    for (const r of list) {
      if (y > H - 180) { doc.addPage(); y = 82; }
      y = renderRecord(doc, r, input.attachmentsByRecord[r.id] ?? [], y, W, H);
      y += 14;
    }
  }

  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    if (page > 1) {
      doc.setFillColor(12, 35, 64);
      doc.rect(0, 0, W, 54, "F");
      if (logo) drawContainedImage(doc, logo.dataUri, "PNG", 48, 10, 34, 34);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      doc.text("MILLSTADT EMS - CONFIDENTIAL PERSONNEL FILE", 94, 31);
    }
    doc.setDrawColor(148, 163, 184);
    doc.line(48, H - 38, W - 48, H - 38);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(page === 1 ? 148 : 100, page === 1 ? 163 : 116, page === 1 ? 184 : 139);
    doc.text(`Employee ID ${input.employee.id}`, 48, H - 22);
    doc.text(`Page ${page} of ${pages}`, W - 48, H - 22, { align: "right" });
  }
  return Buffer.from(doc.output("arraybuffer"));
}

function renderRecord(
  doc: jsPDF,
  r: PersonnelRecord,
  attachments: PersonnelAttachment[],
  yStart: number,
  W: number,
  H: number,
): number {
  let y = yStart;
  const cardX = 48;
  const cardW = W - 96;
  const bottom = H - 54;
  const ensure = (needed: number) => {
    if (y + needed <= bottom) return;
    doc.addPage();
    y = 82;
  };

  const titleLines = doc.splitTextToSize(r.title, cardW - 140);
  ensure(50 + titleLines.length * 14);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.7);
  doc.line(cardX, y, cardX + cardW, y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(20, 30, 60);
  doc.text(titleLines, cardX, y + 22);

  const sev = SEVERITY_COLORS[r.severity] ?? [100, 116, 139];
  doc.setFillColor(...sev);
  doc.roundedRect(cardX + cardW - 96, y + 8, 96, 18, 4, 4, "F");
  doc.setTextColor(255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text(r.severity.toUpperCase(), cardX + cardW - 48, y + 21, { align: "center" });

  y += 22 + 14 * titleLines.length;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(75, 85, 99);
  const meta = [
    r.recordType,
    `Status: ${r.status}`,
    r.incidentDate ? `Event: ${fmtDate(r.incidentDate)}` : null,
    `Created: ${fmtDate(r.createdAt)}`,
    r.employeeVisible ? "Employee-visible" : null,
    r.restrictedVisibility ? "HR-only" : null,
    r.followUpRequired ? `Follow-up: ${fmtDate(r.followUpDueDate)}${r.followUpCompletedAt ? " (done)" : " (open)"}` : null,
    r.acknowledgmentRequired ? (r.acknowledgedAt ? `Acknowledged ${fmtDate(r.acknowledgedAt)}` : "Ack pending") : null,
  ].filter(Boolean).join(" | ");
  const metaLines = doc.splitTextToSize(meta, cardW - 28);
  ensure(metaLines.length * 12 + 8);
  doc.text(metaLines, cardX, y);
  y += 12 * metaLines.length + 4;

  if (r.summary) {
    y = drawBlock(doc, "Summary", r.summary, cardX, cardW, y, H);
  }
  if (r.actionTaken) {
    y = drawBlock(doc, "Action taken", r.actionTaken, cardX, cardW, y, H);
  }
  if (r.workLimitations) {
    y = drawBlock(doc, "Work limitations", r.workLimitations, cardX, cardW, y, H);
  }
  if (r.accommodationType || r.accommodationStart || r.accommodationEnd) {
    const accText =
      [
        r.accommodationType ? `Type: ${r.accommodationType}` : null,
        r.accommodationStart ? `Start: ${fmtDate(r.accommodationStart)}` : null,
        r.accommodationEnd ? `End: ${fmtDate(r.accommodationEnd)}` : null,
        r.accommodationReview ? `Review: ${fmtDate(r.accommodationReview)}` : null,
        r.approvedBy ? `Approved by: ${r.approvedBy}` : null,
      ].filter(Boolean).join(" | ");
    y = drawBlock(doc, "Accommodation", accText, cardX, cardW, y, H);
  }
  if (r.adminNotes) {
    y = drawBlock(doc, "Admin notes (private)", r.adminNotes, cardX, cardW, y, H, true);
  }
  if (r.employeeResponse) {
    y = drawBlock(doc, "Employee response", r.employeeResponse, cardX, cardW, y, H);
  }

  if (attachments.length > 0) {
    if (y + 28 > bottom) { doc.addPage(); y = 82; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(75, 85, 99);
    doc.text("Attached files:", cardX + 14, y); y += 12;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(37, 99, 235);
    doc.setFontSize(8);
    for (const a of attachments) {
      const line = `- [${a.visibilityLevel}] ${a.fileName}`;
      const lines = doc.splitTextToSize(line, cardW - 28);
      if (y + lines.length * 10 > bottom) { doc.addPage(); y = 82; }
      doc.text(lines, cardX, y);
      y += 10 * lines.length;
    }
    y += 4;
  }
  return y + 6;
}

function drawBlock(
  doc: jsPDF,
  label: string,
  value: string,
  cardX: number,
  cardW: number,
  yStart: number,
  pageHeight: number,
  muted = false,
): number {
  let y = yStart;
  const bottom = pageHeight - 54;
  if (y + 28 > bottom) { doc.addPage(); y = 82; }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(muted ? 148 : 100, muted ? 163 : 116, muted ? 184 : 139);
  doc.text(label.toUpperCase(), cardX + 14, y); y += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(muted ? 100 : 30, muted ? 116 : 41, muted ? 139 : 59);
  const lines = doc.splitTextToSize(value, cardW - 28) as string[];
  let index = 0;
  while (index < lines.length) {
    if (y > bottom) { doc.addPage(); y = 82; }
    const count = Math.max(1, Math.floor((bottom - y) / 12) + 1);
    const chunk = lines.slice(index, index + count);
    doc.text(chunk, cardX, y);
    y += 12 * chunk.length + 6;
    index += chunk.length;
    if (index < lines.length) {
      doc.addPage();
      y = 82;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(muted ? 148 : 100, muted ? 163 : 116, muted ? 184 : 139);
      doc.text(`${label.toUpperCase()} (CONTINUED)`, cardX, y);
      y += 10;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(muted ? 100 : 30, muted ? 116 : 41, muted ? 139 : 59);
    }
  }
  return y;
}
