/**
 * Coverage manifest — the single source of truth for "what teaching topics
 * does this app acknowledge?"
 *
 * Every required teaching target appears here exactly once with a clear
 * status (covered / merged-into / out-of-scope / planned). Adding a new
 * teaching target should ALWAYS add a manifest entry; the coverage test
 * fails CI if any required topic is missing.
 *
 * `covered` ≠ `implemented`. Most entries below are `covered` by an
 * unimplemented catalog row — they are acknowledged teaching topics whose
 * waveforms will be built in later phases.
 *
 * Targets are tagged-union pointers (see `coverageTypes.ts`). Use the
 * `rhy()` and `bas()` helpers below for readability.
 */

import {
  type CoverageEntry,
  rhythmTarget,
  basicsTarget,
} from './coverageTypes';

const c = (entry: CoverageEntry): CoverageEntry => entry;
const rhy = rhythmTarget;
const bas = basicsTarget;

export const COVERAGE_MANIFEST: readonly CoverageEntry[] = [
  // ─── Original-prompt: Sinus rhythms ─────────────────────────────────
  c({
    id: 'cov.sinus.normal',
    displayName: 'Normal Sinus Rhythm',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('sinus.normal') },
  }),
  c({
    id: 'cov.sinus.bradycardia',
    displayName: 'Sinus Bradycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('sinus.bradycardia') },
  }),
  c({
    id: 'cov.sinus.tachycardia',
    displayName: 'Sinus Tachycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('sinus.tachycardia') },
  }),
  c({
    id: 'cov.sinus.arrhythmia',
    displayName: 'Sinus Arrhythmia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('sinus.arrhythmia') },
  }),
  c({
    id: 'cov.sinus.arrest',
    displayName: 'Sinus Arrest / Pause',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('sinus.arrest') },
    aliases: ['Sinus Pause'],
  }),

  // ─── Original-prompt: Atrial rhythms ────────────────────────────────
  c({
    id: 'cov.atrial.fib',
    displayName: 'Atrial Fibrillation',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('atrial.fib') },
  }),
  c({
    id: 'cov.atrial.flutter',
    displayName: 'Atrial Flutter',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('atrial.flutter') },
  }),
  c({
    id: 'cov.atrial.svt',
    displayName: 'Supraventricular Tachycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('atrial.svt') },
  }),
  c({
    id: 'cov.atrial.pac',
    displayName: 'Premature Atrial Contractions',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('atrial.pac') },
  }),
  c({
    id: 'cov.atrial.wandering-pacemaker',
    displayName: 'Wandering Atrial Pacemaker',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('atrial.wandering-pacemaker') },
  }),
  c({
    id: 'cov.atrial.mat',
    displayName: 'Multifocal Atrial Tachycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('atrial.mat') },
  }),

  // ─── Original-prompt: Junctional rhythms ────────────────────────────
  c({
    id: 'cov.junctional.rhythm',
    displayName: 'Junctional Rhythm',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('junctional.rhythm') },
  }),
  c({
    id: 'cov.junctional.accelerated',
    displayName: 'Accelerated Junctional Rhythm',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('junctional.accelerated') },
  }),
  c({
    id: 'cov.junctional.tachycardia',
    displayName: 'Junctional Tachycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('junctional.tachycardia') },
  }),
  c({
    id: 'cov.junctional.pjc',
    displayName: 'Premature Junctional Contractions',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('junctional.pjc') },
  }),

  // ─── Original-prompt: Ventricular rhythms ───────────────────────────
  c({
    id: 'cov.vent.pvc',
    displayName: 'Premature Ventricular Contractions',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.pvc') },
  }),
  c({
    id: 'cov.vent.pvc-couplet',
    displayName: 'PVC Couplets',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.pvc-couplet') },
  }),
  c({
    id: 'cov.vent.pvc-triplet',
    displayName: 'PVC Triplets',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.pvc-triplet') },
  }),
  c({
    id: 'cov.vent.bigeminy',
    displayName: 'Ventricular Bigeminy',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.bigeminy') },
  }),
  c({
    id: 'cov.vent.trigeminy',
    displayName: 'Ventricular Trigeminy',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.trigeminy') },
  }),
  c({
    id: 'cov.vent.r-on-t',
    displayName: 'R-on-T PVC',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.r-on-t') },
  }),
  c({
    id: 'cov.vent.idioventricular',
    displayName: 'Idioventricular Rhythm',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.idioventricular') },
  }),
  c({
    id: 'cov.vent.aivr',
    displayName: 'Accelerated Idioventricular Rhythm',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.aivr') },
  }),
  c({
    id: 'cov.vent.vtach-stable',
    displayName: 'Stable Ventricular Tachycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.vtach-stable') },
  }),
  c({
    id: 'cov.vent.vtach-unstable',
    displayName: 'Unstable Ventricular Tachycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.vtach-unstable') },
  }),
  c({
    id: 'cov.vent.vfib',
    displayName: 'Ventricular Fibrillation',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.vfib') },
  }),
  c({
    id: 'cov.vent.torsades',
    displayName: 'Torsades de Pointes',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.torsades') },
  }),
  c({
    id: 'cov.vent.polymorphic-vt',
    displayName: 'Polymorphic Ventricular Tachycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.polymorphic-vt') },
  }),
  c({
    id: 'cov.vent.asystole',
    displayName: 'Asystole',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.asystole') },
  }),
  c({
    id: 'cov.vent.pea',
    displayName: 'Pulseless Electrical Activity',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('vent.pea') },
  }),

  // ─── Original-prompt: AV blocks ─────────────────────────────────────
  c({
    id: 'cov.avb.first-degree',
    displayName: 'First-Degree AV Block',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('av-block.first-degree') },
  }),
  c({
    id: 'cov.avb.mobitz-i',
    displayName: 'Second-Degree AV Block Type I (Wenckebach)',
    category: 'rhythm',
    source: 'original-prompt',
    aliases: ['Wenckebach', 'Mobitz I'],
    status: { kind: 'covered', coveredBy: rhy('av-block.second-mobitz-i') },
  }),
  c({
    id: 'cov.avb.mobitz-ii',
    displayName: 'Second-Degree AV Block Type II (Mobitz II)',
    category: 'rhythm',
    source: 'original-prompt',
    aliases: ['Mobitz II'],
    status: { kind: 'covered', coveredBy: rhy('av-block.second-mobitz-ii') },
  }),
  c({
    id: 'cov.avb.third-degree',
    displayName: 'Third-Degree AV Block (Complete Heart Block)',
    category: 'rhythm',
    source: 'original-prompt',
    aliases: ['CHB'],
    status: { kind: 'covered', coveredBy: rhy('av-block.third-degree') },
  }),
  c({
    id: 'cov.avb.high-grade',
    displayName: 'High-Grade AV Block',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('av-block.high-grade') },
  }),
  c({
    id: 'cov.avb.dissociation',
    displayName: 'AV Dissociation',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('av-block.dissociation') },
  }),

  // ─── Original-prompt: Pacemaker rhythms ─────────────────────────────
  c({
    id: 'cov.pacer.atrial',
    displayName: 'Atrial Paced Rhythm',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('pacer.atrial') },
  }),
  c({
    id: 'cov.pacer.ventricular',
    displayName: 'Ventricular Paced Rhythm',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('pacer.ventricular') },
  }),
  c({
    id: 'cov.pacer.av',
    displayName: 'AV Paced / Dual Chamber Paced Rhythm',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('pacer.av') },
  }),
  c({
    id: 'cov.pacer.failure-to-pace',
    displayName: 'Failure to Pace',
    category: 'pacemaker-malfunction',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('pacer.failure-to-pace') },
  }),
  c({
    id: 'cov.pacer.failure-to-capture',
    displayName: 'Failure to Capture',
    category: 'pacemaker-malfunction',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('pacer.failure-to-capture') },
  }),
  c({
    id: 'cov.pacer.failure-to-sense',
    displayName: 'Failure to Sense',
    category: 'pacemaker-malfunction',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('pacer.failure-to-sense') },
    notes:
      'Closely related to "Undersensing" — both are first-class catalog entries (Option A) so quizzes can present them as separate teaching terms.',
  }),
  c({
    id: 'cov.pacer.oversensing',
    displayName: 'Oversensing',
    category: 'pacemaker-malfunction',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('pacer.oversensing') },
  }),
  c({
    id: 'cov.pacer.undersensing',
    displayName: 'Undersensing',
    category: 'pacemaker-malfunction',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('pacer.undersensing') },
    notes:
      'Kept as a separate first-class entry (Option A) for educational and quiz clarity. See `pacer.failure-to-sense` for the closely related sibling concept.',
  }),

  // ─── Original-prompt: Conduction abnormalities ──────────────────────
  c({
    id: 'cov.conduction.rbbb',
    displayName: 'Right Bundle Branch Block',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('conduction.rbbb') },
  }),
  c({
    id: 'cov.conduction.lbbb',
    displayName: 'Left Bundle Branch Block',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('conduction.lbbb') },
  }),
  c({
    id: 'cov.conduction.wide-complex-tach',
    displayName: 'Wide-Complex Tachycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('conduction.wide-complex-tach') },
  }),
  c({
    id: 'cov.conduction.irregular-wct',
    displayName: 'Irregular Wide-Complex Tachycardia',
    category: 'rhythm',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('conduction.irregular-wct') },
  }),
  c({
    id: 'cov.conduction.wpw',
    displayName: 'WPW / Pre-excitation',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('conduction.wpw') },
  }),
  c({
    id: 'cov.conduction.long-qt',
    displayName: 'Long QT',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('conduction.long-qt') },
  }),
  c({
    id: 'cov.conduction.short-qt',
    displayName: 'Short QT',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('conduction.short-qt') },
  }),
  c({
    id: 'cov.conduction.brugada-pattern',
    displayName: 'Brugada Pattern',
    category: 'channelopathy',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('conduction.brugada-pattern') },
    notes:
      'Umbrella teaching topic for Brugada. Specific morphologies covered separately by `special.brugada-type-1` and `special.brugada-type-2`.',
  }),

  // ─── Original-prompt: Ischemia / STEMI ──────────────────────────────
  c({
    id: 'cov.ischemia.st-depression',
    displayName: 'ST Depression / Ischemia',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.st-depression') },
  }),
  c({
    id: 'cov.ischemia.inferior-stemi',
    displayName: 'Inferior STEMI',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.inferior-stemi') },
  }),
  c({
    id: 'cov.ischemia.anterior-stemi',
    displayName: 'Anterior STEMI',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.anterior-stemi') },
  }),
  c({
    id: 'cov.ischemia.lateral-stemi',
    displayName: 'Lateral STEMI',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.lateral-stemi') },
  }),
  c({
    id: 'cov.ischemia.anterolateral-stemi',
    displayName: 'Anterolateral STEMI',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.anterolateral-stemi') },
  }),
  c({
    id: 'cov.ischemia.septal-stemi',
    displayName: 'Septal STEMI',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.septal-stemi') },
  }),
  c({
    id: 'cov.ischemia.posterior-stemi',
    displayName: 'Posterior STEMI',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.posterior-stemi') },
  }),
  c({
    id: 'cov.ischemia.rv-stemi',
    displayName: 'Right Ventricular STEMI',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.rv-stemi') },
  }),
  c({
    id: 'cov.ischemia.sgarbossa',
    displayName: 'Sgarbossa Criteria',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.sgarbossa') },
  }),
  c({
    id: 'cov.ischemia.modified-sgarbossa',
    displayName: 'Modified Sgarbossa Criteria',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.modified-sgarbossa') },
  }),
  c({
    id: 'cov.ischemia.wellens',
    displayName: 'Wellens Pattern',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.wellens') },
  }),
  c({
    id: 'cov.ischemia.de-winter',
    displayName: 'De Winter Pattern',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.de-winter') },
  }),
  c({
    id: 'cov.ischemia.pericarditis-mimic',
    displayName: 'Pericarditis Mimic',
    category: 'pattern-12-lead',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('ischemia.pericarditis-mimic') },
  }),

  // ─── Original-prompt: Electrolyte / tox ─────────────────────────────
  c({
    id: 'cov.electrolyte.hyperk-peaked-t',
    displayName: 'Hyperkalemia with Peaked T Waves',
    category: 'electrolyte-tox',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.hyperk-peaked-t') },
  }),
  c({
    id: 'cov.electrolyte.hyperk-progression',
    displayName: 'Hyperkalemia Progression',
    category: 'electrolyte-tox',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.hyperk-progression') },
  }),
  c({
    id: 'cov.electrolyte.hyperk-sine-wave',
    displayName: 'Sine-Wave Hyperkalemia Pattern',
    category: 'electrolyte-tox',
    source: 'original-prompt',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.hyperk-sine-wave') },
  }),

  // ═══════════════════════════════════════════════════════════════════
  //  LITFL EXTENSIONS — explicitly requested in the correction pass
  // ═══════════════════════════════════════════════════════════════════
  c({
    id: 'cov.litfl.aslanger',
    displayName: 'Aslanger Pattern',
    category: 'pattern-12-lead',
    source: 'litfl-extension',
    status: { kind: 'covered', coveredBy: rhy('ischemia.aslanger') },
  }),
  c({
    id: 'cov.litfl.south-african-flag',
    displayName: 'South African Flag Sign',
    category: 'pattern-12-lead',
    source: 'litfl-extension',
    status: { kind: 'covered', coveredBy: rhy('ischemia.south-african-flag') },
  }),
  c({
    id: 'cov.litfl.bundgaard',
    displayName: 'Bundgaard Syndrome',
    category: 'channelopathy',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 5, notes: 'Rare channelopathy. Add with the expert pack.' },
  }),
  c({
    id: 'cov.litfl.masquerading-bbb',
    displayName: 'Masquerading Bundle Branch Block',
    category: 'pattern-12-lead',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 6, notes: 'Anterior MI mimicking RBBB; add with the 12-lead pack.' },
  }),
  c({
    id: 'cov.litfl.fusion-beats',
    displayName: 'Fusion Beats',
    category: 'rhythm',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 5, notes: 'Single-beat morphology that combines supraventricular and ventricular activation.' },
  }),
  c({
    id: 'cov.litfl.low-qrs-voltage',
    displayName: 'Low QRS Voltage',
    category: 'pattern-12-lead',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 6, notes: 'Differential includes effusion, COPD, obesity, infiltrative disease.' },
  }),
  c({
    id: 'cov.litfl.motion-artefact',
    displayName: 'ECG Motion Artefact',
    category: 'special-topic',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 1, notes: 'Modeled by `artifacts.ts` once the artifact engine ships in Phase 1.' },
  }),
  c({
    id: 'cov.litfl.myocarditis',
    displayName: 'Myocarditis',
    category: 'pattern-12-lead',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 6, notes: 'STEMI mimic; add with the ischemia/12-lead pack.' },
  }),
  c({
    id: 'cov.litfl.poor-r-wave-progression',
    displayName: 'Poor R Wave Progression',
    category: 'pattern-12-lead',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 6, notes: 'Anterior MI vs. lead misplacement vs. LVH/COPD differential.' },
  }),
  c({
    id: 'cov.litfl.ventricular-flutter',
    displayName: 'Ventricular Flutter',
    category: 'rhythm',
    source: 'litfl-extension',
    status: { kind: 'covered', coveredBy: rhy('vent.flutter') },
  }),
  c({
    id: 'cov.litfl.carbamazepine-toxicity',
    displayName: 'Carbamazepine Toxicity',
    category: 'electrolyte-tox',
    source: 'litfl-extension',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.carbamazepine-toxicity') },
    notes:
      'Split out from the sodium-channel-blocker merge so toxicology teaching can quiz the specific agent.',
  }),
  c({
    id: 'cov.litfl.quetiapine-toxicity',
    displayName: 'Quetiapine Toxicity',
    category: 'electrolyte-tox',
    source: 'litfl-extension',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.quetiapine-toxicity') },
    notes:
      'Split out from the sodium-channel-blocker merge so toxicology teaching can quiz the specific agent.',
  }),
  c({
    id: 'cov.litfl.hyperthyroidism',
    displayName: 'Hyperthyroidism ECG Changes',
    category: 'special-topic',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 6, notes: 'Sinus tach, AFib are the most common findings.' },
  }),
  c({
    id: 'cov.litfl.hypothyroidism',
    displayName: 'Hypothyroidism ECG Changes',
    category: 'special-topic',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 6, notes: 'Sinus brady, low voltage, prolonged QT possible.' },
  }),
  c({
    id: 'cov.litfl.r-wave-peak-time',
    displayName: 'R-Wave Peak Time',
    category: 'basics-concept',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 6, notes: 'Advanced 12-lead measurement; add when basics module is expanded.' },
  }),
  c({
    id: 'cov.litfl.q-wave',
    displayName: 'Q Wave',
    category: 'basics-concept',
    source: 'litfl-extension',
    status: {
      kind: 'merged-into',
      mergedInto: bas('basics.waves.qrs'),
      rationale:
        'Q wave is a component of the QRS complex. The QRS basics concept teaches Q/R/S together; pathological Q is taught in `ischemia.pathologic-q`.',
    },
  }),
  c({
    id: 'cov.litfl.r-wave',
    displayName: 'R Wave',
    category: 'basics-concept',
    source: 'litfl-extension',
    status: {
      kind: 'merged-into',
      mergedInto: bas('basics.waves.qrs'),
      rationale: 'R wave is a component of the QRS complex; taught alongside Q and S in the QRS basics concept.',
    },
  }),
  c({
    id: 'cov.litfl.u-wave',
    displayName: 'U Wave',
    category: 'basics-concept',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 3, notes: 'Will get a dedicated basics concept; for now, U waves are described in the hypokalemia learning notes.' },
  }),
  c({
    id: 'cov.litfl.j-wave',
    displayName: 'J Wave',
    category: 'pattern-12-lead',
    source: 'litfl-extension',
    status: {
      kind: 'merged-into',
      mergedInto: rhy('special.hypothermia'),
      rationale:
        'J (Osborn) waves are taught as part of the hypothermia entry; will get its own basics concept when basics expands.',
    },
  }),
  c({
    id: 'cov.litfl.delta-wave',
    displayName: 'Delta Wave',
    category: 'pattern-12-lead',
    source: 'litfl-extension',
    status: {
      kind: 'merged-into',
      mergedInto: rhy('conduction.wpw'),
      rationale: 'The delta wave is the defining feature of WPW/pre-excitation; taught there.',
    },
  }),
  c({
    id: 'cov.litfl.epsilon-wave',
    displayName: 'Epsilon Wave',
    category: 'pattern-12-lead',
    source: 'litfl-extension',
    status: {
      kind: 'merged-into',
      mergedInto: rhy('special.arvc'),
      rationale: 'The epsilon wave is the diagnostic feature of ARVC; taught there.',
    },
  }),
  c({
    id: 'cov.litfl.pr-segment',
    displayName: 'PR Segment',
    category: 'basics-concept',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 3, notes: 'Distinct from PR interval; PR depression is a key pericarditis feature.' },
  }),
  c({
    id: 'cov.litfl.st-segment',
    displayName: 'ST Segment',
    category: 'basics-concept',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 3, notes: 'Will get a dedicated basics concept covering normal vs elevation/depression.' },
  }),
  c({
    id: 'cov.litfl.j-point',
    displayName: 'J Point',
    category: 'basics-concept',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 3, notes: 'Referenced in `ischemia.early-repolarization` and `ischemia.de-winter`; will get its own basics concept.' },
  }),
  c({
    id: 'cov.litfl.vt-vs-svt',
    displayName: 'VT vs SVT Differentiation',
    category: 'special-topic',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 5, notes: 'Dedicated teaching content (Brugada algorithm, Vereckei aVR, capture/fusion beats).' },
  }),
  c({
    id: 'cov.litfl.pediatric',
    displayName: 'Pediatric ECG Interpretation',
    category: 'pediatric',
    source: 'litfl-extension',
    status: { kind: 'planned', phase: 8, notes: 'Large standalone topic; reasonable to split into a pediatric pack.' },
  }),

  // ═══════════════════════════════════════════════════════════════════
  //  CATALOG-DERIVED — coverage rows for additional catalog rhythms
  //  (so the manifest acknowledges every catalog teaching topic)
  // ═══════════════════════════════════════════════════════════════════
  c({
    id: 'cov.derived.sinus.sa-exit-block',
    displayName: 'Sinoatrial Exit Block',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('sinus.sa-exit-block') },
  }),
  c({
    id: 'cov.derived.sinus.sick-sinus',
    displayName: 'Sick Sinus Syndrome',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('sinus.sick-sinus-syndrome') },
  }),
  c({
    id: 'cov.derived.atrial.fib-rvr',
    displayName: 'Atrial Fibrillation with RVR',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('atrial.fib-rvr') },
  }),
  c({
    id: 'cov.derived.atrial.flutter-atypical',
    displayName: 'Atypical Atrial Flutter',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('atrial.flutter-atypical') },
  }),
  c({
    id: 'cov.derived.atrial.avnrt',
    displayName: 'AV Nodal Reentrant Tachycardia',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('atrial.avnrt') },
  }),
  c({
    id: 'cov.derived.atrial.avrt',
    displayName: 'AV Reentrant Tachycardia',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('atrial.avrt') },
  }),
  c({
    id: 'cov.derived.atrial.focal-at',
    displayName: 'Focal Atrial Tachycardia',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('atrial.focal-atrial-tach') },
  }),
  c({
    id: 'cov.derived.atrial.ectopic-atrial',
    displayName: 'Ectopic Atrial Rhythm',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('atrial.ectopic-atrial-rhythm') },
  }),
  c({
    id: 'cov.derived.atrial.blocked-pac',
    displayName: 'Blocked PAC',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('atrial.blocked-pac') },
  }),
  c({
    id: 'cov.derived.vent.pvc-multifocal',
    displayName: 'Multifocal PVCs',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('vent.pvc-multifocal') },
  }),
  c({
    id: 'cov.derived.vent.quadrigeminy',
    displayName: 'Ventricular Quadrigeminy',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('vent.quadrigeminy') },
  }),
  c({
    id: 'cov.derived.vent.bidirectional-vt',
    displayName: 'Bidirectional VT',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('vent.bidirectional-vt') },
  }),
  c({
    id: 'cov.derived.vent.fascicular-vt',
    displayName: 'Fascicular VT',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('vent.fascicular-vt') },
  }),
  c({
    id: 'cov.derived.vent.rvot-vt',
    displayName: 'RVOT VT',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('vent.rvot-vt') },
  }),
  c({
    id: 'cov.derived.vent.vfib-fine',
    displayName: 'Fine Ventricular Fibrillation',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('vent.vfib-fine') },
  }),
  c({
    id: 'cov.derived.vent.nsvt',
    displayName: 'Non-Sustained VT',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('vent.nsvt') },
  }),
  c({
    id: 'cov.derived.vent.escape',
    displayName: 'Ventricular Escape Beat',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('vent.ventricular-escape') },
  }),
  c({
    id: 'cov.derived.avb.2-1',
    displayName: '2:1 AV Block',
    category: 'rhythm',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('av-block.2-1') },
  }),
  c({
    id: 'cov.derived.pacer.pmt',
    displayName: 'Pacemaker-Mediated Tachycardia',
    category: 'pacemaker-malfunction',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('pacer.pmt') },
  }),
  c({
    id: 'cov.derived.pacer.runaway',
    displayName: 'Runaway Pacemaker',
    category: 'pacemaker-malfunction',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('pacer.runaway') },
  }),
  c({
    id: 'cov.derived.conduction.incomplete-rbbb',
    displayName: 'Incomplete RBBB',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.incomplete-rbbb') },
  }),
  c({
    id: 'cov.derived.conduction.incomplete-lbbb',
    displayName: 'Incomplete LBBB',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.incomplete-lbbb') },
  }),
  c({
    id: 'cov.derived.conduction.lafb',
    displayName: 'Left Anterior Fascicular Block',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.lafb') },
  }),
  c({
    id: 'cov.derived.conduction.lpfb',
    displayName: 'Left Posterior Fascicular Block',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.lpfb') },
  }),
  c({
    id: 'cov.derived.conduction.bifascicular',
    displayName: 'Bifascicular Block',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.bifascicular') },
  }),
  c({
    id: 'cov.derived.conduction.trifascicular',
    displayName: 'Trifascicular Block',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.trifascicular') },
  }),
  c({
    id: 'cov.derived.conduction.nicd',
    displayName: 'Non-Specific Intraventricular Conduction Delay',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.nicd') },
  }),
  c({
    id: 'cov.derived.conduction.wpw-type-a',
    displayName: 'WPW Type A',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.wpw-type-a') },
  }),
  c({
    id: 'cov.derived.conduction.wpw-type-b',
    displayName: 'WPW Type B',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.wpw-type-b') },
  }),
  c({
    id: 'cov.derived.conduction.lgl',
    displayName: 'Lown-Ganong-Levine Pattern',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('conduction.lgl') },
  }),
  c({
    id: 'cov.derived.ischemia.t-wave-inversion',
    displayName: 'T-Wave Inversion',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.t-wave-inversion') },
  }),
  c({
    id: 'cov.derived.ischemia.hyperacute-t',
    displayName: 'Hyperacute T Waves',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.hyperacute-t') },
  }),
  c({
    id: 'cov.derived.ischemia.pathologic-q',
    displayName: 'Pathological Q Waves',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.pathologic-q') },
  }),
  c({
    id: 'cov.derived.ischemia.high-lateral-stemi',
    displayName: 'High Lateral STEMI',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.high-lateral-stemi') },
  }),
  c({
    id: 'cov.derived.ischemia.inferolateral-stemi',
    displayName: 'Inferolateral STEMI',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.inferolateral-stemi') },
  }),
  c({
    id: 'cov.derived.ischemia.left-main',
    displayName: 'Left Main Coronary Occlusion Pattern',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.left-main-occlusion') },
  }),
  c({
    id: 'cov.derived.ischemia.wellens-a',
    displayName: 'Wellens Type A',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.wellens-type-a') },
  }),
  c({
    id: 'cov.derived.ischemia.wellens-b',
    displayName: 'Wellens Type B',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.wellens-type-b') },
  }),
  c({
    id: 'cov.derived.ischemia.lv-aneurysm',
    displayName: 'LV Aneurysm Pattern',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.lv-aneurysm') },
  }),
  c({
    id: 'cov.derived.ischemia.early-repol',
    displayName: 'Early Repolarization (Benign)',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.early-repolarization') },
  }),
  c({
    id: 'cov.derived.ischemia.lvh-strain',
    displayName: 'LVH with Strain Pattern',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('ischemia.lvh-strain') },
  }),
  c({
    id: 'cov.derived.electrolyte.hypok',
    displayName: 'Hypokalemia (U Waves)',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.hypok') },
  }),
  c({
    id: 'cov.derived.electrolyte.hyperca',
    displayName: 'Hypercalcemia',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.hyperca') },
  }),
  c({
    id: 'cov.derived.electrolyte.hypoca',
    displayName: 'Hypocalcemia',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.hypoca') },
  }),
  c({
    id: 'cov.derived.electrolyte.hypermg',
    displayName: 'Hypermagnesemia',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.hypermg') },
  }),
  c({
    id: 'cov.derived.electrolyte.hypomg',
    displayName: 'Hypomagnesemia',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.hypomg') },
  }),
  c({
    id: 'cov.derived.electrolyte.dig-effect',
    displayName: 'Digoxin Effect',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.digoxin-effect') },
  }),
  c({
    id: 'cov.derived.electrolyte.dig-toxicity',
    displayName: 'Digoxin Toxicity',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.digoxin-toxicity') },
  }),
  c({
    id: 'cov.derived.electrolyte.tca',
    displayName: 'TCA Toxicity',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.tca-toxicity') },
  }),
  c({
    id: 'cov.derived.electrolyte.na-channel',
    displayName: 'Sodium-Channel Blocker Toxicity',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.na-channel-blocker') },
  }),
  c({
    id: 'cov.derived.electrolyte.cocaine',
    displayName: 'Cocaine Toxicity',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.cocaine-toxicity') },
  }),
  c({
    id: 'cov.derived.electrolyte.lithium',
    displayName: 'Lithium Toxicity',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.lithium-toxicity') },
  }),
  c({
    id: 'cov.derived.electrolyte.bb-ccb',
    displayName: 'Beta-Blocker / CCB Toxicity',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.bb-ccb-toxicity') },
    notes:
      'Combined teaching entry. Agent-specific siblings exist as `electrolyte.bb-toxicity` and `electrolyte.ccb-toxicity` for differential teaching.',
  }),
  c({
    id: 'cov.derived.electrolyte.bb',
    displayName: 'Beta-Blocker Toxicity',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.bb-toxicity') },
  }),
  c({
    id: 'cov.derived.electrolyte.ccb',
    displayName: 'Calcium-Channel Blocker Toxicity',
    category: 'electrolyte-tox',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('electrolyte.ccb-toxicity') },
  }),
  c({
    id: 'cov.derived.special.brugada-1',
    displayName: 'Brugada Type 1 (Coved)',
    category: 'channelopathy',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.brugada-type-1') },
  }),
  c({
    id: 'cov.derived.special.brugada-2',
    displayName: 'Brugada Type 2 (Saddleback)',
    category: 'channelopathy',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.brugada-type-2') },
  }),
  c({
    id: 'cov.derived.special.arvc',
    displayName: 'Arrhythmogenic RV Cardiomyopathy (ARVC)',
    category: 'channelopathy',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.arvc') },
  }),
  c({
    id: 'cov.derived.special.cpvt',
    displayName: 'Catecholaminergic Polymorphic VT (CPVT)',
    category: 'channelopathy',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.cpvt') },
  }),
  c({
    id: 'cov.derived.special.hcm',
    displayName: 'Hypertrophic Cardiomyopathy (HCM)',
    category: 'special-topic',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.hcm') },
  }),
  c({
    id: 'cov.derived.special.hypothermia',
    displayName: 'Hypothermia (Osborn / J Waves)',
    category: 'special-topic',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.hypothermia') },
  }),
  c({
    id: 'cov.derived.special.pe-pattern',
    displayName: 'Pulmonary Embolism Pattern',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.pe-pattern') },
  }),
  c({
    id: 'cov.derived.special.lvh',
    displayName: 'Left Ventricular Hypertrophy',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.lvh') },
  }),
  c({
    id: 'cov.derived.special.rvh',
    displayName: 'Right Ventricular Hypertrophy',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.rvh') },
  }),
  c({
    id: 'cov.derived.special.lae',
    displayName: 'Left Atrial Enlargement',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.left-atrial-enlargement') },
  }),
  c({
    id: 'cov.derived.special.rae',
    displayName: 'Right Atrial Enlargement',
    category: 'pattern-12-lead',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.right-atrial-enlargement') },
  }),
  c({
    id: 'cov.derived.special.alternans',
    displayName: 'Electrical Alternans',
    category: 'special-topic',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.electrical-alternans') },
  }),
  c({
    id: 'cov.derived.special.dextrocardia',
    displayName: 'Dextrocardia',
    category: 'special-topic',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.dextrocardia') },
  }),
  c({
    id: 'cov.derived.special.lead-reversal',
    displayName: 'Limb Lead Reversal',
    category: 'special-topic',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.lead-reversal') },
  }),
  c({
    id: 'cov.derived.special.takotsubo',
    displayName: 'Takotsubo Cardiomyopathy',
    category: 'special-topic',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.takotsubo') },
  }),
  c({
    id: 'cov.derived.special.cerebral-t',
    displayName: 'Cerebral T Waves',
    category: 'special-topic',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.cerebral-t-waves') },
  }),
  c({
    id: 'cov.derived.special.athlete-heart',
    displayName: "Athlete's Heart Pattern",
    category: 'special-topic',
    source: 'project-derived',
    status: { kind: 'covered', coveredBy: rhy('special.athlete-heart') },
  }),

  // ═══════════════════════════════════════════════════════════════════
  //  BASICS — coverage entries for every concept in `basics.ts`
  // ═══════════════════════════════════════════════════════════════════
  c({
    id: 'cov.basics.paper-small-box',
    displayName: 'ECG Paper — Small Box',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.paper.small-box') },
  }),
  c({
    id: 'cov.basics.paper-large-box',
    displayName: 'ECG Paper — Large Box',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.paper.large-box') },
  }),
  c({
    id: 'cov.basics.standard-12-leads',
    displayName: '12 Standard Leads',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.leads.standard-12') },
  }),
  c({
    id: 'cov.basics.precordial-placement',
    displayName: 'Precordial Lead Placement',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.leads.placement') },
  }),
  c({
    id: 'cov.basics.p-wave',
    displayName: 'P Wave',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.waves.p-wave') },
  }),
  c({
    id: 'cov.basics.qrs',
    displayName: 'QRS Complex',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.waves.qrs') },
  }),
  c({
    id: 'cov.basics.t-wave',
    displayName: 'T Wave',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.waves.t-wave') },
  }),
  c({
    id: 'cov.basics.q-wave',
    displayName: 'Q Wave',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.waves.q-wave') },
  }),
  c({
    id: 'cov.basics.r-wave',
    displayName: 'R Wave',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.waves.r-wave') },
  }),
  c({
    id: 'cov.basics.s-wave',
    displayName: 'S Wave',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.waves.s-wave') },
  }),
  c({
    id: 'cov.basics.u-wave',
    displayName: 'U Wave',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.waves.u-wave') },
  }),
  c({
    id: 'cov.basics.delta-wave',
    displayName: 'Delta Wave',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.waves.delta-wave') },
  }),
  c({
    id: 'cov.basics.pr-segment',
    displayName: 'PR Segment',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.segments.pr-segment') },
  }),
  c({
    id: 'cov.basics.st-segment',
    displayName: 'ST Segment',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.segments.st-segment') },
  }),
  c({
    id: 'cov.basics.tp-segment',
    displayName: 'TP Segment',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.segments.tp-segment') },
  }),
  c({
    id: 'cov.basics.j-point',
    displayName: 'J Point',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.segments.j-point') },
  }),
  c({
    id: 'cov.basics.baseline',
    displayName: 'Isoelectric Baseline',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.segments.baseline') },
  }),
  c({
    id: 'cov.basics.calibration',
    displayName: 'Calibration Pulse',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.segments.calibration') },
  }),
  c({
    id: 'cov.basics.pr-interval',
    displayName: 'PR Interval',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.intervals.pr') },
  }),
  c({
    id: 'cov.basics.qrs-duration',
    displayName: 'QRS Duration',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.intervals.qrs-duration') },
  }),
  c({
    id: 'cov.basics.qt-interval',
    displayName: 'QT Interval',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.intervals.qt') },
  }),
  c({
    id: 'cov.basics.rr-interval',
    displayName: 'R–R Interval',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.intervals.rr') },
  }),
  c({
    id: 'cov.basics.pp-interval',
    displayName: 'P–P Interval',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.intervals.pp') },
  }),
  c({
    id: 'cov.basics.rate-300',
    displayName: 'Rate Calculation — 300 Method',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.rate.300-method') },
  }),
  c({
    id: 'cov.basics.rate-6sec',
    displayName: 'Rate Calculation — 6-Second Method',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.rate.6-second') },
  }),
  c({
    id: 'cov.basics.axis-quadrant',
    displayName: 'Cardiac Axis Quadrant Method',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.axis.quadrant') },
  }),
  c({
    id: 'cov.basics.systematic-approach',
    displayName: 'Systematic ECG Approach',
    category: 'basics-concept',
    source: 'litfl-basics',
    status: { kind: 'covered', coveredBy: bas('basics.approach.systematic') },
  }),
];

export const COVERAGE_BY_ID: ReadonlyMap<string, CoverageEntry> = new Map(
  COVERAGE_MANIFEST.map((entry) => [entry.id, entry]),
);

export function getCoverage(id: string): CoverageEntry | undefined {
  return COVERAGE_BY_ID.get(id);
}
